use study;
select * from class;
select * from class_discipline;
select * from discipline;
select * from exam;
select * from exam_result;
select * from speciality;
select * from speciality_discipline;
select * from student;
select * from student_result;
select * from teacher;
select * from teacher_degree;
select * from teacher_discipline;
