-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 11:04:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cleaning_agency
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cleaning_agency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cleaning_agency` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cleaning_agency` ;

-- -----------------------------------------------------
-- Table `cleaning_agency`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaning_agency`.`users` (
  `id_user` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `password` VARCHAR(15) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `role` ENUM('admin', 'client', 'cleaner', 'guest') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `name` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `lastname` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `phone` BIGINT(20) UNSIGNED NOT NULL,
  `address` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaning_agency`.`cleaners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaning_agency`.`cleaners` (
  `id_cleaner` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT(20) UNSIGNED NOT NULL,
  `commission` DECIMAL(3,2) NULL DEFAULT NULL,
  `notes` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_cleaner`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`id_user`)
    REFERENCES `cleaning_agency`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaning_agency`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaning_agency`.`clients` (
  `id_client` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT(20) UNSIGNED NOT NULL,
  `discount` DECIMAL(3,2) NULL DEFAULT NULL,
  `location` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `relative` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `notes` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `user_idx` (`id_user` ASC) VISIBLE,
  INDEX `user_client_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `user_client`
    FOREIGN KEY (`id_user`)
    REFERENCES `cleaning_agency`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaning_agency`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaning_agency`.`orders` (
  `id_order` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_time` DATE NULL DEFAULT NULL,
  `deadline` DATE NULL DEFAULT NULL,
  `order_status` ENUM('new', 'registered', 'in process', 'done', 'declined') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `mark` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `id_client` BIGINT(20) UNSIGNED NOT NULL,
  `id_cleaner` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_order`),
  UNIQUE INDEX `id_UNIQUE` (`id_order` ASC) VISIBLE,
  INDEX `client_idx` (`id_client` ASC) VISIBLE,
  INDEX `cleaner_idx` (`id_cleaner` ASC) VISIBLE,
  CONSTRAINT `cleaner`
    FOREIGN KEY (`id_cleaner`)
    REFERENCES `cleaning_agency`.`cleaners` (`id_cleaner`),
  CONSTRAINT `client`
    FOREIGN KEY (`id_client`)
    REFERENCES `cleaning_agency`.`clients` (`id_client`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaning_agency`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaning_agency`.`services` (
  `id_service` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `cost` DECIMAL(5,2) NULL DEFAULT NULL,
  `sales` DECIMAL(3,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaning_agency`.`basket_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaning_agency`.`basket_position` (
  `id_basket` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_order` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `id_service` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_basket`),
  INDEX `order_idx` (`id_order` ASC) VISIBLE,
  INDEX `service_idx` (`id_service` ASC) VISIBLE,
  CONSTRAINT `order`
    FOREIGN KEY (`id_order`)
    REFERENCES `cleaning_agency`.`orders` (`id_order`),
  CONSTRAINT `service`
    FOREIGN KEY (`id_service`)
    REFERENCES `cleaning_agency`.`services` (`id_service`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
